name: celery_test

services:
  rabbit:
    image: rabbitmq:management-alpine
    container_name: celery_rabbit
    hostname: rabbit
    networks:
      - compose-network
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  redis:
    image: redis/redis-stack
    container_name: celery_redis
    hostname: redis
    networks:
      - compose-network
    ports:
      - "6379:6379"
      - "8001:8001"


networks:
  compose-network:
    driver: bridge
